### PR TITLE
Use standard '&' separator instead of ',' for KV pairs in URI query

### PR DESCRIPTION
**Pull request by rdumusc**
This is to allow parsing query parameters in http GET request in the standard form "host:rest/image?format=png&size=256,256" (see [RFC6570](https://tools.ietf.org/html/rfc6570))

This change will probably imply adaptating existing scripts commands (fivox, webservice..?), but I hope we can make it happen :-)

### CODE REVIEW

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by eile** [comment]
We should emit a warning if we encounter a value matching ```.*,.*=```

**Comment by rdumusc** [comment]
Warning implemented!

**Comment by eile** [comment]
Looks good to me - ping to @tribal-tec since this will have a fun impact, although I see no alternative.

**Comment by rdumusc** [comment]
Yes, it will have an impact in multiple places. Everybody needs to agree with the change and be ready to adapt their existing URIs.

**Comment by tribal-tec** [comment]
fine with me as well. You prepared downstream projects already (not easy to guess where it's used 'wrong' I guess...)?

**Comment by rdumusc** [comment]
Changes are ready for Fivox + LFP and Cubist, mostly documentation updates. I could not find more occurrences in the code base, and according to Cyrille the webservices should not be impacted. So I suggest to go ahead with the change.

**Comment by rdumusc** [comment]
retest this please

**Pull request merged**
