### PR TITLE
Events

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
@chevtche, @tribal-tec : I thought a bit about our leaving-elevator discussion that with ZeroBuf we lost support for pure events (i.e. something happened without payload). I think this can be modeled nicely with some syntactic sugar -- see above. Usage would then be 
```
Event event( "zerobuf::render::Exit", myExitFunc );
_subscriber.subscribe( event );
_publisher.publish( event );
```

Only problem I see is that the app needs to keep the event instance alive during subscription - ideas?

**Comment by rdumusc** [comment]
Interesting idea, FYI I was also experimenting with a "Command" object for Qt, a sort of intermediate between an Event (no payload) and an object (which stores its payload). Here it is:

```
/**
 * Handle rest commands in JSON format.
 */
class RestCommand : public QObject, public servus::Serializable
{
    Q_OBJECT

public:
    RestCommand( const std::string& name )
        : _name( name )
    {}

    std::string getTypeName() const final { return _name; }

signals:
    void received( QString data );

private:
    std::string _name;

    bool _fromJSON( const std::string& json ) override
    {
        Json::Value json;
        Json::Reader reader;
        if( !reader.parse( string, json ))
            return false;

        const std::string name = json["uri"].asString();
        emit received( QString::fromStdString( name ));
        return true;
    }
};
```

I also wanted to find a way to pass the REST Query parameters to the updatedFunc, however I could not find an elegant way without breaking the API as it is typdef'ed (void).

**Comment by bilgili** [comment]
I was already modifying the zeq::Event as a servus::serializable.

**Comment by bilgili** [comment]
Instead of keeping the pointers to serializable objects in the subscriber, shallow copies can be kept. As Data object is the shared_ptr this should be easy. I am trying to scope.

**Comment by eile** [comment]
@bilgili : The old zeq::Event has flatbuffers payload and should become something like a flatbuffer::Serializable. In this draft here, the event is just an event with no payload, e.g., for EXIT.

**Comment by eile** [comment]
Shallow copies: I'ld rather then change the API to take shared_ptr< Serializable > instead of requiring the Serializable to be shallow-copyable.

**Comment by bilgili** [comment]
I thought serializable:.Data was an object shared between instances. It was easy to construct an object around it. But as I have more insight, shared_ptr<Serializable> is a better option but problem is, code will be a bit ugly while using.

**Comment by bilgili** [comment]
What is the state of the servus::Event ? I will need it for Monsteer.

**Comment by eile** [comment]
This one was just a draft for @chevtche . Superseeded by HBPVIS/ZeroEQ#152

**Pull request closed without merging**
