### PR TITLE
Support "host:port" URIs, fix some tests and mistakes in parser

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by eile** [comment]
uri = "file.txt" won't work anymore?

**Comment by hernando** [comment]
I haven't look deeply into the changes, but the new parsing doesn't seem to be parsing URIs according to the RFC (https://tools.ietf.org/html/rfc3986) anymore.
To give an example, the Python3 function urllib.parse.urlparse does this:

    In[1]: urllib.parse.urlparse('host:8080')
    Out[1]: ParseResult(scheme='', netloc='', path='host:8080', params='', query='', fragment='')

Which is what our current parser does if I'm not mistaken.

Why do you need an empty schema?

What are the mistakes that you fixed? It's not obvious due the the big changes introduced.

**Comment by eile** [comment]
Maybe we're not RFC-strict (were we ever?), but at least at the application level entering host:port is typically a valid URI.

**Comment by hernando** [comment]
But /absolute/path and ./relative/path should also be valid URIs.

**Comment by tribal-tec** [comment]
- file.txt would be file://file.txt. Like file:12345 is ambiguous anyways if schema is missing.
- counter question: why do I need a schema to express "host:8080"? In ZeroEQ, the schema won't be needed anymore, and browsers also accept host:port w/o any schema.
- If you want a file URI, where host:port could be a valid filename as well, put file:// as schema,

**Comment by tribal-tec** [comment]
The mistakes I fixed are visible from the unit tests. I can put them to the Changelog, but I only if we find a consensus here what changes we do if any. If host:port is not a parseable as host and port, then I vote to use host and port as separate parameters for ZeroEQ objects and get rid of the URI there entirely.

**Comment by hernando** [comment]
My comments come from the fact that I tried to adhere to the generic syntax from the RFC when I wrote the parser, and that's what the documentation says. I'm fine with accepting *host:port* as a valid URI, but then the documentation has to be updated. If none of the dependent packages is relying on */file* being a valid URI, this can also be changed to require *file:///*.

I'd prefer if the description of the mistakes fixed are at least part of the commit message.

**Comment by tribal-tec** [comment]
After yesterday's discussion, this is not needed anymore. I'll push a small review for fixing some parts though.

**Pull request closed without merging**
