### PR TITLE
Fix OS X build

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by hernando** [comment]
There are merge conflicts

**Comment by hernando** [comment]
I've merged it manually

**Comment by hernando** [comment]
Sorry, I got confused with https://github.com/hernando/Lunchbox/pull/1

**Comment by hernando** [comment]
The conflicting commit was mine. Could you please rebase?

**Comment by eile** [comment]
Done

**Comment by eile** [comment]
Retest this please.

**Pull request merged**
