### PR TITLE
Fix cppcheck warnings

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
@rdumusc please review

**Comment by rdumusc** [comment]
+2

**Comment by eile** [comment]
retest this please

**Comment by eile** [comment]
retest this please

**Comment by rdumusc** [comment]
retest this please

**Comment by eile** [comment]
Thanks - seems to be an issue with my user. Escalating with Infra once more.

**Comment by rdumusc** [comment]
Yes, I was checking quickly but I don't know what's happening to you. Your membership to BlueBrain on github is public and you are in the admin list of the Servus plan in Jenkins, so it should be fine...

**Pull request merged**
