### PR TITLE
Replace ChangeFunc by ChangeSignal in serializable

### PR DESCRIPTION
**Pull request by jafyvilla**
servus::serializable now uses boost::signals for the change
notifications instead of functions. They are exposed as public
members, so they can be assigned/emitted directly.

### CODE REVIEW

**Comment by rdumusc** [comment]
I am against introducing a hard dependency on boost in such a low level API. The callback functions were a bit more verbose, but perfectly functional. Plus we have to adapt dependent code once again.

**Comment by bilgili** [comment]
I highly agree with @rdumusc. What will be the advantage over the function objects ? Multiple objects can listen the same change ? This is rarely used and can be handled explicitly.

**Comment by tribal-tec** [comment]
* Current callback feature supports only one active callback. Multiple callbacks requires callback registry etc. which a signal/slot framework already provides. In the end it boils down to reinvent the wheel vs. use something existing.
* Boost dependency is not nice, agreed. In practice, for our environment it won't be an issue. Speed is an issue with boost.signals at a certain number of slots. There are different other header-only implementations (https://github.com/pbhogan/Signals, more on google) which would alleviate those facts. In the worst case, the signal implemenation could be hidden as the interface to expose is minimal. In general, signal/slot is an elegant way of the observer pattern that C++ lacks unfortunately, the D language fixed that by making part of their standard library.
* Downstream code adaption is not a strong argument for a non-stable API library. Servus itself should be one (as discussed offline; Servus should only provided network discovery), but then a Serializable library would not be stable now as we have not used it yet and are about discover, discuss and implement use-cases, changes, etc.

**Comment by bilgili** [comment]
How often needed ? If we are improving the API for a specific case it may not be the right solution. An adapter class can provide a signal one end and function in another end, a very simple solution for a simple use case.

**Comment by eile** [comment]
It is needed for:
* co::Distributable
* Redraw in Livre (and likely others)
* Publish triggers (ie https://github.com/BlueBrain/Fivox/blob/master/fivox/progressObserver.cpp#L93 should be on signal to only publish on change)

**Comment by bilgili** [comment]
- co::Distributable is concern of Collage which no project except Equalizer uses.
- 2-3 Can be solved using an adapter

**Comment by eile** [comment]
I don't get it: This change removes 80 loc while adding a much needed functionality. co::Distributable transparently wraps Serializables for Eq distribution, so either this gets more complicated (why?) or it has to be figured out between co and Servus. How is adding multiplexing externally better? I don't remember the impl in livreGUI being of particular beauty. Let's discuss after the standup.

We decided years ago that boost is one of the standard dependencies we can use everywhere when needed.

**Pull request closed without merging**
